import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

const dir = new URL('./dictionaries/', import.meta.url).pathname;
const en = JSON.parse(readFileSync(join(dir, 'en.json'), 'utf8'));

function write(name, obj) {
  writeFileSync(join(dir, `${name}.json`), JSON.stringify(obj, null, 2) + '\n');
  console.log(`Wrote ${name}.json`);
}

/* ---------- helper: clone en and replace leaf values ---------- */
function skeleton(en, overrides) {
  const result = {};
  for (const [k, v] of Object.entries(en)) {
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
      result[k] = overrides?.[k] ? skeleton(v, overrides[k]) : skeleton(v);
    } else {
      result[k] = overrides?.[k] ?? v; // fallback to English
    }
  }
  return result;
}

/* ======================== SPANISH ======================== */
const es = {
  site: { title: "Proyecto de Recuperación Civilizacional", shortTitle: "PRC", description: "El conocimiento completo necesario para reconstruir la civilización desde cero." },
  nav: { home: "Inicio", survival: "Supervivencia", science: "Ciencia", engineering: "Ingeniería", medicine: "Medicina", agriculture: "Agricultura", industry: "Industria", library: "Biblioteca", downloads: "Descargas" },
  aria: { toggleSidebar: "Alternar barra lateral", searchLibrary: "Buscar en la biblioteca", toggleDarkMode: "Alternar modo oscuro", primaryNav: "Principal", breadcrumb: "Migas de pan", knowledgeTree: "Árbol de conocimiento", rebuildLadder: "Escalera de reconstrucción", techGraph: "Grafo interactivo de dependencias tecnológicas" },
  footer: { mission: "Misión", missionText: "El Proyecto de Recuperación Civilizacional preserva el conocimiento operativo de la humanidad — las instrucciones para hacerlo todo de nuevo — en un archivo offline-first, listo para imprimir. No es un sitio web. Es una copia de seguridad de la civilización.", knowledgeSections: "Secciones de conocimiento", downloads: "Descargas", offlineLibrary: "Biblioteca offline", printableEdition: "Edición imprimible", fullLibraryIndex: "Índice completo", sourceZIP: "Código fuente ZIP", openSource: "Código abierto · Libre para copiar, imprimir y redistribuir" },
  home: { heroTagline: "Copia operativa de la humanidad · Offline-first · Listo para imprimir", heroTitle1: "Proyecto de Recuperación", heroTitle2: "Civilizacional", heroSubtitle: "El conocimiento completo necesario para reconstruir la civilización desde cero — un camino estructurado, validado y reproducible desde una fogata hasta un programa espacial.", startLearning: "Empezar a Aprender", browseLibrary: "Explorar Biblioteca", downloadPrint: "Descargar / Imprimir", statsArticles: "Artículos de conocimiento", statsStages: "Etapas de recuperación", statsOffline: "Listo para offline", statsDeps: "Dependencias externas", reconstructionPath: "El camino de reconstrucción", tenStages: "Diez etapas. Cada una desbloquea la siguiente.", tenStagesDesc: "El progreso es estrictamente ordenado — cada etapa contiene el conocimiento necesario para alcanzar la siguiente. No se pueden saltar peldaños.", level: "Nivel", coreKnowledge: "Conocimiento básico", deepDives: "Profundizaciones — la ruta crítica", interactiveTree: "Árbol tecnológico interactivo →", designPrinciples: "Principios de diseño", builtForPermanence: "Construido para la permanencia", offlineFirst: "Offline-first", offlineFirstDesc: "Cada artículo es HTML estático. Descarga el ZIP y toda la biblioteca funciona sin electricidad, red ni servidores.", printIsPermanent: "La impresión es permanente", printIsPermanentDesc: "Las redes eléctricas fallan. Las pantallas mueren. El papel sobrevive a ambas.", validatedReproducible: "Validado y reproducible", validatedReproducibleDesc: "Cada procedimiento enumera materiales, herramientas, pasos y la ciencia detrás — reproducible con tecnología disponible progresivamente." },
  about: { title: "Sobre el Proyecto de Recuperación Civilizacional", intro: "Esta es una base de conocimiento de código abierto y offline-first para reiniciar la civilización humana — construida en el espíritu del anime Dr. Stone y basada en la ciencia real de la recuperación del conocimiento.", whyExists: "Por qué existe", whyExistsText: "Si la civilización colapsara, el recurso más valioso sería el conocimiento: no el oro, no las máquinas, sino las instrucciones para hacer cosas desde cero. Los sobrevivientes modernos saben usar cosas pero no hacer cosas. Este sitio es un intento de cerrar esa brecha con un árbol tecnológico práctico y ordenado.", theSources: "Las fuentes", sourceDrStone: "Dr. Stone — la progresión tecnológica escalonada (piedra → hierro → electricidad → radio), y la idea de que el conocimiento es una aventura que se puede recorrer de nuevo.", sourceInfoPreserver: "El Proyecto InfoPreserver (Lifeboat Foundation) — los niveles de capacidad de la Escalera de Reconstrucción A0–A5 que organizan este sitio.", sourceKnowledge: "The Knowledge: How to Rebuild Our World from Scratch de Lewis Dartnell — el método científico de recuperación de la civilización.", sourceOSE: "Open Source Ecology / Global Village Construction Set — planos abiertos de las 50 máquinas que inician un asentamiento moderno.", sourceSurvival: "Tradiciones de supervivencia y bushcraft — los fundamentos de baja tecnología que mantienen a la gente viva.", howToUse: "Cómo usarlo", step1: "Empieza en A0 — agua, fuego, refugio. El mínimo no es opcional.", step2: "Sigue la prioridad de supervivencia — agua, refugio, comida, higiene, luego herramientas.", step3: "Sigue los prerrequisitos — cada guía enumera lo que necesitas antes.", step4: "Saques primero — cada guía enumera lo que los escombros ya proporcionan.", step5: "Enseña e imprime — copia las guías, pásalas e imprime las páginas críticas. El papel sobrevive a las redes.", thePrinciples: "Los principios", principleDigital: "Lo digital es temporal. La impresión es permanente.", principleRedundancy: "La redundancia salva el conocimiento — tres personas deben saber cada habilidad crítica.", principleCompounds: "El conocimiento se acumula — la escalera es más rápida en cada peldaño porque los anteriores se vuelven más fáciles.", contribute: "Contribuir", contributeText: "Este es un trabajo en progreso, construido incrementalmente. El árbol de contenido está abierto y estructurado para crecer.", quote: "\"La humanidad es ciencia. Eso es todo lo que somos.\" — Senku Ishigami, Dr. Stone" },
  downloads: { title: "Descargas", tagline: "Lo digital es temporal. La impresión es permanente.", subtitle: "Este archivo está diseñado para ser movido, copiado e impreso. Las redes eléctricas fallan. Las pantallas mueren. El papel y los archivos que posees no.", recommended: "Recomendado", fullArchiveTitle: "Descargar Archivo Completo", fullArchiveDesc: "Toda la biblioteca como archivos estáticos — cada artículo, cada guía, cada diagrama. Descarga una vez, abre en cualquier dispositivo sin red, sin servidor, sin electricidad.", fullArchiveAction: "Descargar ZIP", printableTitle: "Edición Imprimible", printableDesc: "Botones de impresión por guía, CSS limpio para impresión y paquetes de capítulos por etapa.", printableAction: "Abrir paquetes de impresión", sourceTitle: "Repositorio Fuente", sourceDesc: "El código fuente markdown de cada artículo, versionado en GitHub y libremente redistribuible.", sourceAction: "Ver en GitHub", version: "Versión", lastUpdated: "Última actualización", articles: "Artículos", totalSize: "Tamaño total", fitsUSB: "Cabe en cualquier USB", redundancyDoctrine: "Doctrina de redundancia", rule1Strong: "Tres copias, dos medios, una lejos.", rule1Text: " Mantén una copia digital, una copia impresa y una copia de seguridad sellada almacenada por separado.", rule2Strong: "Imprime maestros, luego copia.", rule2Text: " Mantén un juego maestro seco y sellado; haz copias de trabajo.", rule3Strong: "Copia el ZIP en múltiples dispositivos", rule3Text: " — un teléfono, una laptop, una memoria USB, un e-reader viejo. Los dispositivos fallan; las copias sobreviven.", rule4Strong: "Enséñalo.", rule4Text: " El formato más duradero es una persona que puede explicar el conocimiento a la siguiente generación." },
  library: { title: "Biblioteca", tagline: "Índice completo", subtitle: "Cada artículo de conocimiento en el archivo, filtrable por etapa y buscable por texto.", filteredTo: "Actualmente filtrado por etapa", searchPlaceholder: "Buscar artículos…", allStages: "Todas las etapas", articlesCount: "{count} artículos" },
  search: { title: "Buscar", tagline: "Encuéntralo rápido", subtitle: "Busca cada guía por título, categoría o palabra clave. Funciona completamente en tu navegador — funciona offline.", searchPlaceholder: "Buscar artículos, palabras clave, categorías…", articlesCount: "{count} artículos", articlesOf: "{visible} de {total} artículos", noResults: "Ningún artículo coincide. Prueba con una palabra clave más amplia, o empieza en la Biblioteca." },
  techTree: { title: "Árbol Tecnológico", tagline: "Grafo interactivo de dependencias", subtitle: "Cada nodo es una tecnología con una guía completa. Las flechas apuntan de los prerrequisitos a lo que desbloquean.", criticalPath: "Naranja", criticalPathText: " marca la ruta crítica;", missingReq: "rojo punteado", missingReqText: " marca una guía cuyo prerrequisito aún no está en la biblioteca.", graphView: "Vista de grafo", listView: "Vista de lista", rules: "Reglas del árbol", rule1: "No puedes saltar la escalera.", rule1Desc: " Cada guía enumera sus prerrequisitos. Un motor de vapor sin hierro es un rumor.", rule2: "Saques antes de construir.", rule2Desc: " Cada guía enumera lo que los escombros ya proporcionan.", rule3: "Enseña todo.", rule3Desc: " Una tecnología que solo una persona conoce está a un accidente de perderse.", rule4: "Imprime las guías.", rule4Desc: " El papel sobrevive. Las redes no. Mira los ", rule4Link: "paquetes de impresión", legendMastered: "Dominado", legendAvailable: "Disponible", legendLocked: "Bloqueado", legendCritical: "Ruta crítica", legendMissing: "Prerrequisito faltante", resetProgress: "Reiniciar progreso", resetConfirm: "¿Reiniciar todo el progreso de dominio en este dispositivo?" },
  techArticle: { home: "Inicio", library: "Biblioteca", level: "Nivel", risk: "Riesgo", coreTechnology: "Tecnología básica", difficulty: "Dificultad", levelRequired: "Nivel requerido", studyTime: "Tiempo de estudio", stage: "Etapa", requiredKnowledge: "Conocimiento requerido", noPrerequisites: "Sin prerrequisitos — esta es una tecnología fundamental.", knowledgeValidation: "Validación de conocimiento", allChecksPass: "Todas las verificaciones pasan.", specifications: "Especificaciones", materials: "Materiales", energy: "Energía", people: "Personas", reference: "Referencia", scavengeBeforeBuilding: "Saques antes de construir", unlocksNext: "Desbloquea siguiente", dependencies: "Dependencias", noDependencies: "Sin dependencias.", markAsMastered: "Marcar como dominado", masteredUndo: "Dominado — clic para deshacer", printThisGuide: "Imprimir esta guía", exportOptions: "Opciones de exportación", relatedArticles: "Artículos relacionados", prereqComplete: "Prerrequisitos completos", scientificVerified: "Precisión científica verificada", illustrationsIncluded: "Ilustraciones incluidas", printReady: "Listo para imprimir", offlineReady: "Listo para offline", pathValid: "Ruta de reconstrucción válida" },
  ladder: { title: "La Escalera de Reconstrucción", framework: "El marco", subtitle: "Inspirada en la escalera de capacidad del proyecto InfoPreserver y la progresión tecnológica escalonada de Dr. Stone.", drStoneParallel: "Paralelo con Dr. Stone", backToLadder: "← La Escalera", noteUnresolved: "Nota: {titles} referencian tecnologías fuera de este árbol." },
  print: { title: "Paquetes de Impresión", tagline: "El papel sobrevive", subtitle: "Las redes eléctricas fallan. Las pantallas mueren. El papel es permanente.", starterKit: "El Kit de Supervivencia", starterKitDesc: "Todo en A0 — agua, fuego, refugio, primeros auxilios. Las primeras 48 horas de un reinicio.", starterKitAction: "Abrir todas las guías A0", starterKitTip: "Imprime cada página de guía desde el diálogo de impresión de tu navegador.", communityManual: "El Manual Comunitario", communityManualDesc: "A1 — agricultura, conservación, jabón, saneamiento. El primer año de un asentamiento.", communityManualAction: "Abrir todas las guías A1", bootstrappersPack: "El Paquete del Pionero", bootstrappersPackDesc: "A2 — carbón, hierro, ácido sulfúrico, vapor, electricidad. La etapa más difícil y valiosa.", bootstrappersPackAction: "Abrir todas las guías A2", printingTips: "Consejos de impresión", tip1Strong: "Calidad del papel:", tip1Text: " el papel de algodón sin ácido dura décadas; el papel de copiar común dura años.", tip2Strong: "Tinta:", tip2Text: " el tóner de láser es mucho más resistente al agua que la tinta.", tip3Strong: "Laminado:", tip3Text: " para las páginas que usarás al aire libre — agua, fuego, primeros auxilios.", tip4Strong: "Reproducción:", tip4Text: " una fotocopiadora es en sí una tecnología que vale la pena preservar.", tip5Strong: "Distribución:", tip5Text: " mantén un juego maestro sellado y seco; haz copias de trabajo." },
  levels: {
    A0: { name: "Base de Supervivencia", timeframe: "Días – Semanas", question: "¿Pueden los humanos seguir vivos?", description: "Agua, fuego, refugio, primeros auxilios y las primeras herramientas hechas a mano. El suelo absoluto para mantener a un grupo vivo.", drStone: "Los primeros tres meses de Senku: herramientas de piedra, cuerda, taladro de arco, fuego." },
    A1: { name: "Comunidad Estabilizada", timeframe: "Meses – Años", question: "¿Puede la gente vivir aquí de manera sostenible?", description: "Agricultura, conservación de alimentos, refugio permanente, saneamiento, jabón y las estructuras sociales que permiten que un pueblo persista.", drStone: "Aldea Ishigami: agricultura, cerámica, tejido, una forma de vida asentada." },
    A2: { name: "Semilla Industrial", timeframe: "Años – Décadas", question: "¿Podemos iniciar la industria?", description: "El punto de aceleración no lineal. Carbón, hierro, químicos, el torno, vapor y electricidad desbloquean todo lo después. La etapa más difícil y valiosa.", drStone: "El Reino de la Ciencia: alto horno, ácido sulfúrico, generadores, radio." },
    A3: { name: "Recuperación de Infraestructura", timeframe: "Décadas", question: "¿Pueden los sistemas escalar más allá de un pueblo?", description: "Acueductos regionales, redes eléctricas, redes ferroviarias y sistemas de salud pública que unen muchas comunidades.", drStone: "El Perseus, GPS, represas hidroeléctricas, carreteras pavimentadas." },
    A4: { name: "Industria y Ciencia Avanzada", timeframe: "Generaciones", question: "Precisión, optimización, investigación", description: "Electrónica de transistores, circuitos integrados, química y farmacéutica modernas, y el retorno de la investigación científica como institución.", drStone: "La ruta del silicio, tubos de vacío, el computador parametrón." },
    A5: { name: "Frontera y Saltos", timeframe: "Horizonte Lejano", question: "Sistemas de alta dependencia para sociedades futuras", description: "Aeroespacial, satélites y biotecnología avanzada. Solo vale la pena construir después de que la escalera inferior sea sólida.", drStone: "La misión lunar, contacto con Why-Man." }
  },
  stages: {
    survival: { name: "Supervivencia", question: "¿Podemos seguir vivos?", description: "Agua, fuego, refugio y las primeras herramientas hechas a mano." },
    settlement: { name: "Asentamiento", question: "¿Podemos vivir aquí permanentemente?", description: "Refugio permanente, saneamiento, higiene y comunidad." },
    agriculture: { name: "Agricultura", question: "¿Podemos alimentarnos de forma fiable?", description: "Agricultura, conservación de semillas, preservación y ganadería." },
    craftsmanship: { name: "Artesanía", question: "¿Podemos hacer cosas bien?", description: "Cerámica, textiles, vidrio, papel y la mentalidad de precisión." },
    metallurgy: { name: "Metalurgia", question: "¿Podemos extraer y dar forma al metal?", description: "Carbón, hierro, acero, cobre — los materiales de todo lo demás." },
    engineering: { name: "Ingeniería", question: "¿Podemos construir máquinas?", description: "Medición, el torno, energía hidráulica y la máquina de vapor." },
    electricity: { name: "Electricidad", question: "¿Podemos aprovechar el electrón?", description: "Generadores, baterías y el árbol de comunicaciones." },
    industry: { name: "Industria", question: "¿Pueden los sistemas escalar más allá de un pueblo?", description: "Química a escala, transporte e infraestructura regional." },
    digital: { name: "Tecnología Digital", question: "¿Podemos computar de nuevo?", description: "Electrónica, computación y el retorno de la investigación." },
    space: { name: "Era Espacial", question: "¿Podemos dejar la cuna?", description: "Aeroespacial, cohetes y sistemas de alta dependencia." }
  },
  sections: {
    survival: { title: "Supervivencia", subtitle: "Prioridad 1 — mantener a la gente viva", description: "Agua, fuego, refugio, comida, higiene y primeros auxilios. El suelo absoluto de la escalera." },
    settlement: { title: "Asentamiento", subtitle: "Prioridad 2 — vivir aquí permanentemente", description: "Refugio permanente, saneamiento y las estructuras sociales que permiten que un pueblo persista." },
    agriculture: { title: "Agricultura", subtitle: "Prioridad 2 — alimentar a la gente de forma fiable", description: "Agricultura, conservación de semillas, preservación de alimentos y ganadería." },
    medicine: { title: "Medicina", subtitle: "Prioridad 1 — la infección mata más que la lesión", description: "Cuidado de heridas, higiene, conocimiento herbal y los límites honestos de la medicina de baja tecnología." },
    science: { title: "Ciencia", subtitle: "Prioridad 4 — el método detrás de la reconstrucción", description: "El método científico hecho físico: medición, química y los experimentos reproducibles." },
    engineering: { title: "Ingeniería", subtitle: "Prioridad 3 — máquinas y energía", description: "Mecánica, materiales, metalurgia y las máquinas que multiplican el músculo humano." },
    industry: { title: "Industria", subtitle: "Prioridad 5 — escalar más allá de un pueblo", description: "Fabricación, químicos, transporte y comunicación a escala regional." }
  },
  sidebar: {
    knowledgeTree: "Árbol de conocimiento",
    groups: {
      survival: { label: "Supervivencia", subsections: { "s-water": "Agua", "s-shelter": "Refugio", "s-fire": "Fuego", "s-food": "Comida", "s-med": "Medicina", "s-tools": "Herramientas y Materiales" } },
      science: { label: "Ciencia", subsections: { "c-chem": "Química", "c-measure": "Medición" } },
      engineering: { label: "Ingeniería", subsections: { "e-met": "Metalurgia", "e-mach": "Máquinas", "e-power": "Energía", "e-comms": "Comunicación" } },
      community: { label: "Comunidad", subsections: { "g-gov": "Gobernanza" } }
    }
  },
  categories: { Survival: "Supervivencia", Shelter: "Refugio", "Food & Water": "Comida y Agua", Community: "Comunidad", Power: "Energía", Metallurgy: "Metalurgia", Chemistry: "Química", "Machine Tools": "Herramientas", Communications: "Comunicaciones", Transport: "Transporte", Metrology: "Metrología", Infrastructure: "Infraestructura", Electronics: "Electrónica", Computing: "Computación", Frontier: "Frontera" },
  safety: { LOW: "Bajo riesgo", MODERATE: "Riesgo moderado", HIGH: "Alto riesgo", EXTREME: "Riesgo extremo" },
  common: { home: "Inicio", articles: "artículos", articleCount: "{count} artículos", level: "Nivel", core: "Básico", mastered: "Dominado", available: "Disponible", locked: "Bloqueado", criticalPath: "Ruta crítica", missingPrerequisite: "Prerrequisito faltante" }
};
write('es', es);

/* ======================== FRENCH ======================== */
const fr = {
  site: { title: "Projet de Récupération Civilisationnelle", shortTitle: "PRC", description: "Les connaissances complètes nécessaires pour reconstruire la civilisation desde zéro." },
  nav: { home: "Accueil", survival: "Survie", science: "Science", engineering: "Ingénierie", medicine: "Médecine", agriculture: "Agriculture", industry: "Industrie", library: "Bibliothèque", downloads: "Téléchargements" },
  aria: { toggleSidebar: "Basculer la barre latérale", searchLibrary: "Rechercher dans la bibliothèque", toggleDarkMode: "Basculer le mode sombre", primaryNav: "Principal", breadcrumb: "Fil d'Ariane", knowledgeTree: "Arbre de connaissances", rebuildLadder: "Échelle de reconstruction", techGraph: "Graphe interactif de dépendances technologiques" },
  footer: { mission: "Mission", missionText: "Le Projet de Récupération Civilisationnelle préserve les connaissances opérationnelles de l'humanité — les instructions pour tout refaire — dans une archive hors ligne, prête à imprimer. Ce n'est pas un site web. C'est une copie de sauvegarde de la civilisation.", knowledgeSections: "Sections de connaissances", downloads: "Téléchargements", offlineLibrary: "Bibliothèque hors ligne", printableEdition: "Édition imprimable", fullLibraryIndex: "Index complet", sourceZIP: "Code source ZIP", openSource: "Open source · Libre à copier, imprimer et redistribuer" },
  home: { heroTagline: "Copie opérationnelle de l'humanité · Hors ligne · Prêt à imprimer", heroTitle1: "Projet de Récupération", heroTitle2: "Civilisationnelle", heroSubtitle: "Les connaissances complètes nécessaires pour reconstruire la civilisation — un chemin structuré, validé et reproductible d'un feu de camp à un programme spatial.", startLearning: "Commencer à apprendre", browseLibrary: "Parcourir la bibliothèque", downloadPrint: "Télécharger / Imprimer", statsArticles: "Articles de connaissances", statsStages: "Étapes de récupération", statsOffline: "Prêt hors ligne", statsDeps: "Dépendances externes", reconstructionPath: "Le chemin de reconstruction", tenStages: "Dix étapes. Chaque ouvre la suivante.", tenStagesDesc: "La progression est strictement ordonnée — chaque étape contient les connaissances nécessaires pour atteindre la suivante.", level: "Niveau", coreKnowledge: "Connaissances fondamentales", deepDives: "Approfondissements — le chemin critique", interactiveTree: "Arbre technologique interactif →", designPrinciples: "Principes de conception", builtForPermanence: "Conçu pour la permanence", offlineFirst: "Hors ligne d'abord", offlineFirstDesc: "Chaque article est du HTML statique. Téléchargez le ZIP et toute la bibliothèque fonctionne sans électricité, réseau ou serveurs.", printIsPermanent: "L'impression est permanente", printIsPermanentDesc: "Les réseaux électriques tombent en panne. Les écrans meurent. Le papier survit aux deux.", validatedReproducible: "Validé et reproductible", validatedReproducibleDesc: "Chaque procédure énumère les matériaux, outils, étapes et la science derrière — reproductible avec une technologie progressivement disponible." },
  about: { title: "À propos du Projet de Récupération Civilisationnelle", intro: "Ceci est une base de connaissances open source et hors ligne pour redémarrer la civilisation humaine — construite dans l'esprit de l'anime Dr. Stone et fondée sur la science réelle de la récupération des connaissances.", whyExists: "Pourquoi cela existe", whyExistsText: "Si la civilisation s'effondrait, la ressource la plus précieuse serait les connaissances : pas l'or, pas les machines, mais les instructions pour faire les choses desde zéro.", theSources: "Les sources", sourceDrStone: "Dr. Stone — la progression technologique par étapes (pierre → fer → électricité → radio).", sourceInfoPreserver: "Le Projet InfoPreserver (Lifeboat Foundation) — les niveaux de capacité de l'Échelle de Reconstruction A0–A5.", sourceKnowledge: "The Knowledge de Lewis Dartnell — la méthode scientifique de récupération de la civilisation.", sourceOSE: "Open Source Ecology / Global Village Construction Set — plans ouverts des 50 machines.", sourceSurvival: "Traditions de survie et bushcraft — les fondamentaux basse technologie.", howToUse: "Comment l'utiliser", step1: "Commencez à A0 — eau, feu, abri.", step2: "Suivez la priorité de survie — eau, abri, nourriture, hygiène.", step3: "Suivez les prérequis — chaque guide énumère ce dont vous avez besoin.", step4: "Récupérez d'abord — chaque guide énumère ce que les ruines fournissent déjà.", step5: "Enseignez et imprimez — copiez les guides, transmettez-les.", thePrinciples: "Les principes", principleDigital: "Le numérique est temporaire. L'impression est permanente.", principleRedundancy: "La redondance sauve les connaissances — trois personnes doivent maîtriser chaque compétence critique.", principleCompounds: "Les connaissances s'accumulent — l'échelle est plus rapide à chaque échelon.", contribute: "Contribuer", contributeText: "C'est un travail en cours, construit de manière incrémentale.", quote: "\"L'humanité est la science. C'est tout ce que nous sommes.\" — Senku Ishigami, Dr. Stone" },
  downloads: { title: "Téléchargements", tagline: "Le numérique est temporaire. L'impression est permanente.", subtitle: "Cette archive est conçue pour être déplacée, copiée et imprimée.", recommended: "Recommandé", fullArchiveTitle: "Télécharger l'archive complète", fullArchiveDesc: "Toute la bibliothèque en fichiers statiques — chaque article, guide et diagramme.", fullArchiveAction: "Télécharger ZIP", printableTitle: "Édition imprimable", printableDesc: "Boutons d'impression par guide, CSS propre et packs de chapitres par étape.", printableAction: "Ouvrir les packs d'impression", sourceTitle: "Dépôt source", sourceDesc: "La source markdown de chaque article, versionnée sur GitHub.", sourceAction: "Voir sur GitHub", version: "Version", lastUpdated: "Dernière mise à jour", articles: "Articles", totalSize: "Taille totale", fitsUSB: "Tient sur une clé USB", redundancyDoctrine: "Doctrine de redondance", rule1Strong: "Trois copies, deux supports, une éloignée.", rule1Text: " Gardez une copie numérique, une imprimée et une sauvegarde scellée.", rule2Strong: "Imprimez les masters, puis copiez.", rule2Text: " Gardez un jeu master sec et scellé.", rule3Strong: "Copiez le ZIP sur plusieurs appareils", rule3Text: " — téléphone, ordinateur, clé USB.", rule4Strong: "Enseignez-le.", rule4Text: " Le format le plus durable est une personne qui peut transmettre les connaissances." },
  library: { title: "Bibliothèque", tagline: "Index complet", subtitle: "Chaque article de connaissances, filtrable par étape et recherchable par texte.", filteredTo: "Filtré par étape", searchPlaceholder: "Rechercher des articles…", allStages: "Toutes les étapes", articlesCount: "{count} articles" },
  search: { title: "Recherche", tagline: "Trouvez-le vite", subtitle: "Recherchez chaque guide par titre, catégorie ou mot-clé. Fonctionne entièrement dans votre navigateur — hors ligne.", searchPlaceholder: "Rechercher articles, mots-clés, catégories…", articlesCount: "{count} articles", articlesOf: "{visible} sur {total} articles", noResults: "Aucun article ne correspond. Essayez un mot-clé plus large, ou commencez à la Bibliothèque." },
  techTree: { title: "Arbre Technologique", tagline: "Graphe interactif de dépendances", subtitle: "Chaque nœud est une technologie avec un guide complet.", criticalPath: "Orange", criticalPathText: " marque le chemin critique;", missingReq: "rouge pointillé", missingReqText: " marque un guide dont le prérequis n'est pas encore dans la bibliothèque.", graphView: "Vue graphe", listView: "Vue liste", rules: "Règles de l'arbre", rule1: "Vous ne pouvez pas sauter l'échelle.", rule1Desc: " Chaque guide énumère ses prérequis.", rule2: "Récupérez avant de construire.", rule2Desc: " Chaque guide énumère ce que les ruines fournissent déjà.", rule3: "Enseignez tout.", rule3Desc: " Une technologie que seule une personne connaît est à un accident de se perdre.", rule4: "Imprimez les guides.", rule4Desc: " Le papier survit. Les réseaux non. Voir les ", rule4Link: "packs d'impression", legendMastered: "Maîtrisé", legendAvailable: "Disponible", legendLocked: "Verrouillé", legendCritical: "Chemin critique", legendMissing: "Prérequis manquant", resetProgress: "Réinitialiser la progression", resetConfirm: "Réinitialiser toute la progression de maîtrise sur cet appareil ?" },
  techArticle: { home: "Accueil", library: "Bibliothèque", level: "Niveau", risk: "Risque", coreTechnology: "Technologie de base", difficulty: "Difficulté", levelRequired: "Niveau requis", studyTime: "Temps d'étude", stage: "Étape", requiredKnowledge: "Connaissances requises", noPrerequisites: "Aucun prérequis — c'est une technologie fondamentale.", knowledgeValidation: "Validation des connaissances", allChecksPass: "Toutes les vérifications passent.", specifications: "Spécifications", materials: "Matériaux", energy: "Énergie", people: "Personnes", reference: "Référence", scavengeBeforeBuilding: "Récupérer avant de construire", unlocksNext: "Débloque ensuite", dependencies: "Dépendances", noDependencies: "Aucune dépendance.", markAsMastered: "Marquer comme maîtrisé", masteredUndo: "Maîtrisé — cliquer pour annuler", printThisGuide: "Imprimer ce guide", exportOptions: "Options d'exportation", relatedArticles: "Articles connexes", prereqComplete: "Prérequis complets", scientificVerified: "Précision scientifique vérifiée", illustrationsIncluded: "Illustrations incluses", printReady: "Prêt à imprimer", offlineReady: "Prêt hors ligne", pathValid: "Chemin de reconstruction valide" },
  ladder: { title: "L'Échelle de Reconstruction", framework: "Le cadre", subtitle: "Inspirée par l'échelle de capacité du projet InfoPreserver et la progression technologique de Dr. Stone.", drStoneParallel: "Parallèle Dr. Stone", backToLadder: "← L'Échelle", noteUnresolved: "Note : {titles} référencent des technologies en dehors de cet arbre." },
  print: { title: "Packs d'Impression", tagline: "Le papier survit", subtitle: "Les réseaux tombent en panne. Les écrans meurent. Le papier est permanent.", starterKit: "La Kit de Démarrage", starterKitDesc: "Tout en A0 — eau, feu, abri, premiers secours.", starterKitAction: "Ouvrir tous les guides A0", starterKitTip: "Imprimez chaque page via le dialogue d'impression de votre navigateur.", communityManual: "Le Manuel Communautaire", communityManualDesc: "A1 — agriculture, conservation, savon, assainissement.", communityManualAction: "Ouvrir tous les guides A1", bootstrappersPack: "Le Pack du Pionnier", bootstrappersPackDesc: "A2 — charbon, fer, acide sulfurique, vapeur, électricité.", bootstrappersPackAction: "Ouvrir tous les guides A2", printingTips: "Conseils d'impression", tip1Strong: "Qualité du papier :", tip1Text: " le papier sans acide dure des décennies.", tip2Strong: "Encre :", tip2Text: " le toner laser est plus résistant à l'eau.", tip3Strong: "Laminage :", tip3Text: " pour les pages utilisées à l'extérieur.", tip4Strong: "Reproduction :", tip4Text: " un photocopieur est une technologie à préserver.", tip5Strong: "Distribution :", tip5Text: " gardez un jeu master scellé." },
  levels: {
    A0: { name: "Base de Survie", timeframe: "Jours – Semaines", question: "Les humains peuvent-ils rester en vie ?", description: "Eau, feu, abri, premiers secours et les premiers outils fabriqués à la main.", drStone: "Les trois premiers mois de Senku : outils en pierre, corde, foret à arché, feu." },
    A1: { name: "Communauté Stabilisée", timeframe: "Mois – Années", question: "Les gens peuvent-ils vivre ici de manière durable ?", description: "Agriculture, conservation des aliments, abri permanent, assainissement, savon.", drStone: "Village d'Ishigami : agriculture, poterie, tissage, mode de vie sédentaire." },
    A2: { name: "Graine Industrielle", timeframe: "Années – Décennies", question: "Pouvons-nous lancer l'industrie ?", description: "Le point d'accélération non linéaire. Charbon, fer, chimie, tour, vapeur et électricité.", drStone: "Le Royaume de la Science : haut fourneau, acide sulfurique, générateurs, radio." },
    A3: { name: "Récupération d'Infrastructure", timeframe: "Décennies", question: "Les systèmes peuvent-ils s'étendre au-delà d'un village ?", description: "Réseaux hydrauliques régionaux, grilles électriques, chemins de fer.", drStone: "Le Perseus, GPS, barrages hydroélectriques, routes pavées." },
    A4: { name: "Industrie et Science Avancées", timeframe: "Générations", question: "Précision, optimisation, recherche", description: "Électronique à transistors, circuits intégrés, chimie moderne.", drStone: "La route du silicium, tubes à vide, ordinateur paramétron." },
    A5: { name: "Frontière et Sauts", timeframe: "Horizon lointain", question: "Systèmes à haute dépendance pour les sociétés futures", description: "Aérospatial, satellites et biotechnologie avancée.", drStone: "La mission lunaire, contact avec Why-Man." }
  },
  stages: {
    survival: { name: "Survie", question: "Pouvons-nous rester en vie ?", description: "Eau, feu, abri et les premiers outils fabriqués à la main." },
    settlement: { name: "Établissement", question: "Pouvons-nous vivre ici définitivement ?", description: "Abri permanent, assainissement, hygiène et communauté." },
    agriculture: { name: "Agriculture", question: "Pouvons-nous nous nourrir de manière fiable ?", description: "Agriculture, sauvegarde des semences, conservation et élevage." },
    craftsmanship: { name: "Artisanat", question: "Pouvons-nous bien faire les choses ?", description: "Poterie, textiles, verre, papier et l'état d'esprit de précision." },
    metallurgy: { name: "Métallurgie", question: "Pouvons-nous extraire et façonner le métal ?", description: "Charbon, fer, acier, cuivre — les matériaux de tout le reste." },
    engineering: { name: "Ingénierie", question: "Pouvons-nous construire des machines ?", description: "Mesure, tour, énergie hydraulique et machine à vapeur." },
    electricity: { name: "Électricité", question: "Pouvons-nous exploiter l'électron ?", description: "Générateurs, batteries et l'arbre de communication." },
    industry: { name: "Industrie", question: "Les systèmes peuvent-ils s'étendre au-delà d'un village ?", description: "Chimie à grande échelle, transport et infrastructure régionale." },
    digital: { name: "Technologie Digitale", question: "Pouvons-nous calculer à nouveau ?", description: "Électronique, informatique et le retour de la recherche." },
    space: { name: "Ère Spatiale", question: "Pouvons-nous quitter le berceau ?", description: "Aérospatial, fuséerie et systèmes à haute dépendance." }
  },
  sections: {
    survival: { title: "Survie", subtitle: "Priorité 1 — garder les gens en vie", description: "Eau, feu, abri, nourriture, hygiène et premiers secours." },
    settlement: { title: "Établissement", subtitle: "Priorité 2 — vivre ici définitivement", description: "Abri permanent, assainissement et structures sociales." },
    agriculture: { title: "Agriculture", subtitle: "Priorité 2 — nourrir les gens de manière fiable", description: "Agriculture, sauvegarde des semences, conservation et élevage." },
    medicine: { title: "Médecine", subtitle: "Priorité 1 — l'infection tue plus que les blessures", description: "Soins de plaies, hygiène, connaissances herboristes." },
    science: { title: "Science", subtitle: "Priorité 4 — la méthode derrière la reconstruction", description: "La méthode scientifique rendue physique : mesure, chimie et expériences reproductibles." },
    engineering: { title: "Ingénierie", subtitle: "Priorité 3 — machines et énergie", description: "Mécanique, matériaux, métallurgie et machines." },
    industry: { title: "Industrie", subtitle: "Priorité 5 — s'étendre au-delà d'un village", description: "Fabrication, chimie, transport et communication à l'échelle régionale." }
  },
  sidebar: {
    knowledgeTree: "Arbre de connaissances",
    groups: {
      survival: { label: "Survie", subsections: { "s-water": "Eau", "s-shelter": "Abri", "s-fire": "Feu", "s-food": "Nourriture", "s-med": "Médecine", "s-tools": "Outils et Matériaux" } },
      science: { label: "Science", subsections: { "c-chem": "Chimie", "c-measure": "Mesure" } },
      engineering: { label: "Ingénierie", subsections: { "e-met": "Métallurgie", "e-mach": "Machines", "e-power": "Énergie", "e-comms": "Communication" } },
      community: { label: "Communauté", subsections: { "g-gov": "Gouvernance" } }
    }
  },
  categories: { Survival: "Survie", Shelter: "Abri", "Food & Water": "Nourriture et Eau", Community: "Communauté", Power: "Énergie", Metallurgy: "Métallurgie", Chemistry: "Chimie", "Machine Tools": "Outils", Communications: "Communications", Transport: "Transport", Metrology: "Métrologie", Infrastructure: "Infrastructure", Electronics: "Électronique", Computing: "Informatique", Frontier: "Frontière" },
  safety: { LOW: "Faible risque", MODERATE: "Risque modéré", HIGH: "Risque élevé", EXTREME: "Risque extrême" },
  common: { home: "Accueil", articles: "articles", articleCount: "{count} articles", level: "Niveau", core: "Basique", mastered: "Maîtrisé", available: "Disponible", locked: "Verrouillé", criticalPath: "Chemin critique", missingPrerequisite: "Prérequis manquant" }
};
write('fr', fr);

/* ======================== CHINESE (skeleton) ======================== */
const zhOverrides = {
  site: { title: "文明重建项目", shortTitle: "CRP", description: "从零开始重建文明所需的全部知识。" },
  nav: { home: "首页", survival: "生存", science: "科学", engineering: "工程", medicine: "医学", agriculture: "农业", industry: "工业", library: "图书馆", downloads: "下载" },
  aria: { toggleSidebar: "切换导航侧栏", searchLibrary: "搜索图书馆", toggleDarkMode: "切换暗色模式" },
  footer: { mission: "使命", knowledgeSections: "知识板块", downloads: "下载", offlineLibrary: "离线图书馆", printableEdition: "可打印版本", fullLibraryIndex: "完整索引", sourceZIP: "源代码 ZIP", openSource: "开源 · 可自由复制、打印和再分发" },
  home: { heroTagline: "人类的离线备份 · 离线优先 · 可打印", startLearning: "开始学习", browseLibrary: "浏览图书馆", downloadPrint: "下载 / 打印", statsArticles: "知识文章", statsStages: "恢复阶段", statsOffline: "离线可用", statsDeps: "无外部依赖", level: "等级", coreKnowledge: "核心知识", deepDives: "深入研究 — 关键路径", interactiveTree: "交互式技术树 →", designPrinciples: "设计原则", builtForPermanence: "为永久而建", offlineFirst: "离线优先", offlineFirstDesc: "每篇文章都是静态HTML。下载ZIP即可在无电力、网络或服务器的环境下使用整个图书馆。", printIsPermanent: "打印即永久", printIsPermanentDesc: "电网会故障。屏幕会损坏。纸张比两者都持久。", validatedReproducible: "已验证且可复现", validatedReproducibleDesc: "每个流程都列出材料、工具、步骤和背后的科学。" },
  about: { title: "关于文明重建项目", intro: "这是一个开源的离线知识库，用于重启人类文明——以动画《石纪元》的精神构建，基于知识恢复的真实科学。", whyExists: "为什么需要它", whyExistsText: "如果文明崩溃，最有价值的资源将是知识。", theSources: "信息来源", howToUse: "如何使用", thePrinciples: "原则", contribute: "贡献", contributeText: "这是一个持续构建中的项目。" },
  downloads: { title: "下载", tagline: "数字是暂时的。打印是永久的。", recommended: "推荐", fullArchiveTitle: "下载完整档案", fullArchiveAction: "下载 ZIP", printableTitle: "可打印版本", printableAction: "打开打印包", sourceTitle: "源代码仓库", sourceAction: "在 GitHub 上查看", version: "版本", lastUpdated: "最后更新", articles: "文章", totalSize: "总大小", fitsUSB: "可装入任何 U 盘", redundancyDoctrine: "冗余原则" },
  library: { title: "图书馆", tagline: "完整索引", subtitle: "档案中每一篇知识文章，可按阶段筛选和文本搜索。", searchPlaceholder: "搜索文章…", allStages: "所有阶段" },
  search: { title: "搜索", tagline: "快速查找", subtitle: "按标题、类别或关键词搜索每篇指南。完全在浏览器中运行——离线可用。", searchPlaceholder: "搜索文章、关键词、类别…" },
  techTree: { title: "技术树", tagline: "交互式依赖图", graphView: "图形视图", listView: "列表视图", rules: "树的规则", resetProgress: "重置进度", resetConfirm: "重置此设备上的所有掌握进度？" },
  techArticle: { home: "首页", library: "图书馆", level: "等级", risk: "风险", coreTechnology: "核心技术", difficulty: "难度", levelRequired: "所需等级", studyTime: "学习时间", stage: "阶段", requiredKnowledge: "所需知识", noPrerequisites: "无前置要求——这是一项基础技术。", knowledgeValidation: "知识验证", allChecksPass: "所有验证通过。", specifications: "规格", materials: "材料", energy: "能源", people: "人力", reference: "参考", scavengeBeforeBuilding: "建造前先搜集", unlocksNext: "解锁下一项", dependencies: "依赖项", noDependencies: "无依赖项。", markAsMastered: "标记为已掌握", masteredUndo: "已掌握 — 点击撤销", printThisGuide: "打印此指南", exportOptions: "导出选项", relatedArticles: "相关文章" },
  ladder: { title: "重建阶梯", framework: "框架", drStoneParallel: "石纪元对应", backToLadder: "← 阶梯" },
  print: { title: "打印包", tagline: "纸张永存", subtitle: "电网会故障。屏幕会损坏。纸张是永久的。", starterKit: "入门套件", starterKitDesc: "A0 的一切——水、火、庇护、急救。重启的最初48小时。", starterKitAction: "打开所有 A0 指南", communityManual: "社区手册", communityManualDesc: "A1——农业、保存、肥皂、卫生。定居点的第一年。", communityManualAction: "打开所有 A1 指南", bootstrappersPack: "启动者套件", bootstrappersPackDesc: "A2——木炭、铁、硫酸、蒸汽、电力。最困难和最有价值的阶段。", bootstrappersPackAction: "打开所有 A2 指南", printingTips: "打印提示" },
  levels: {
    A0: { name: "生存基线", timeframe: "天 – 周", question: "人类能否存活？", description: "水、火、庇护、急救和第一批手工工具。", drStone: "石科技的前三个月：石器、绳索、弓钻、火。" },
    A1: { name: "稳定社区", timeframe: "月 – 年", question: "人们能否可持续地生活？", description: "农业、食物保存、永久庇护、卫生、肥皂。", drStone: "石神村：农耕、陶器、编织、定居生活。" },
    A2: { name: "工业种子", timeframe: "年 – 十年", question: "我们能否启动工业？", description: "非线性加速点。木炭、铁、化学、车床、蒸汽和电力解锁一切。", drStone: "科学王国：高炉、硫酸、发电机、无线电。" },
    A3: { name: "基础设施恢复", timeframe: "数十年", question: "系统能否超越一个城镇？", description: "区域供水、电网、铁路网络。", drStone: "珀尔修斯号、GPS、水电站大坝。" },
    A4: { name: "先进工业与科学", timeframe: "数代人", question: "精确、优化、研究", description: "晶体管电子、集成电路、现代化学。", drStone: "硅之路、真空管、参变管计算机。" },
    A5: { name: "前沿与跃迁", timeframe: "远期", question: "面向未来社会的高依赖系统", description: "航空航天、卫星和先进生物技术。", drStone: "月球任务、与Why-Man的接触。" }
  },
  stages: {
    survival: { name: "生存", question: "我们能存活吗？", description: "水、火、庇护和第一批手工工具。" },
    settlement: { name: "定居", question: "我们能永久住在这里吗？", description: "永久庇护、卫生和社区。" },
    agriculture: { name: "农业", question: "我们能可靠地养活自己吗？", description: "农业、种子保存、食物保存和畜牧。" },
    craftsmanship: { name: "工艺", question: "我们能做出好东西吗？", description: "陶器、纺织、玻璃、纸张和精确思维。" },
    metallurgy: { name: "冶金", question: "我们能提取和塑造金属吗？", description: "木炭、铁、钢、铜——一切的材料基础。" },
    engineering: { name: "工程", question: "我们能制造机器吗？", description: "测量、车床、水力和蒸汽机。" },
    electricity: { name: "电力", question: "我们能驾驭电子吗？", description: "发电机、电池和通信树。" },
    industry: { name: "工业", question: "系统能否超越一个城镇？", description: "大规模化学、运输和区域基础设施。" },
    digital: { name: "数字技术", question: "我们能再次计算吗？", description: "电子、计算和研究的回归。" },
    space: { name: "太空时代", question: "我们能离开摇篮吗？", description: "航空航天、火箭和高依赖系统。" }
  },
  sections: {
    survival: { title: "生存", subtitle: "优先级1 — 保持人们活着", description: "水、火、庇护、食物、卫生和急救。阶梯的绝对底线。" },
    settlement: { title: "定居", subtitle: "优先级2 — 永久居住", description: "永久庇护、卫生和让村庄跨越季节和世代的社会结构。" },
    agriculture: { title: "农业", subtitle: "优先级2 — 可靠地养活人们", description: "农业、种子保存、食物保存和畜牧。" },
    medicine: { title: "医学", subtitle: "优先级1 — 感染比伤害更致命", description: "伤口护理、卫生、草药知识。" },
    science: { title: "科学", subtitle: "优先级4 — 重建背后的方法", description: "物质化的科学方法：测量、化学和可重复实验。" },
    engineering: { title: "工程", subtitle: "优先级3 — 机器和能源", description: "机械、材料、冶金和倍增人力的机器。" },
    industry: { title: "工业", subtitle: "优先级5 — 超越一个城镇的规模", description: "区域规模的制造、化学、运输和通信。" }
  },
  sidebar: { knowledgeTree: "知识树", groups: { survival: { label: "生存", subsections: { "s-water": "水", "s-shelter": "庇护", "s-fire": "火", "s-food": "食物", "s-med": "医学", "s-tools": "工具与材料" } }, science: { label: "科学", subsections: { "c-chem": "化学", "c-measure": "测量" } }, engineering: { label: "工程", subsections: { "e-met": "冶金", "e-mach": "机器", "e-power": "能源", "e-comms": "通信" } }, community: { label: "社区", subsections: { "g-gov": "治理" } } } },
  categories: { Survival: "生存", Shelter: "庇护", "Food & Water": "食物与水", Community: "社区", Power: "能源", Metallurgy: "冶金", Chemistry: "化学", "Machine Tools": "机床", Communications: "通信", Transport: "运输", Metrology: "计量", Infrastructure: "基础设施", Electronics: "电子", Computing: "计算", Frontier: "前沿" },
  safety: { LOW: "低风险", MODERATE: "中等风险", HIGH: "高风险", EXTREME: "极高风险" },
  common: { home: "首页", articles: "篇文章", level: "等级", core: "核心", mastered: "已掌握", available: "可用", locked: "已锁定", criticalPath: "关键路径", missingPrerequisite: "缺少前置" }
};
const zh = skeleton(en, zhOverrides);
write('zh', zh);

/* ======================== ARABIC (skeleton) ======================== */
const arOverrides = {
  site: { title: "مشروع التعافي الحضاري", shortTitle: "PC", description: "المعرفة الكاملة اللازمة لإعادة بناء الحضارة من الصفر." },
  nav: { home: "الرئيسية", survival: "البقاء", science: "العلوم", engineering: "الهندسة", medicine: "الطب", agriculture: "الزراعة", industry: "الصناعة", library: "المكتبة", downloads: "التحميلات" },
  aria: { toggleSidebar: "تبديل الشريط الجانبي", searchLibrary: "البحث في المكتبة", toggleDarkMode: "تبديل الوضع الداكن" },
  footer: { mission: "المهمة", knowledgeSections: "أقسام المعرفة", downloads: "التحميلات", offlineLibrary: "المكتبة دون اتصال", printableEdition: "نسخة قابلة للطباعة", fullLibraryIndex: "الفهرس الكامل", sourceZIP: "الكود المصدري ZIP", openSource: "مفتوح المصدر · حر في النسخ والطباعة وإعادة التوزيع" },
  home: { heroTagline: "نسخة احتياطية تشغيلية للبشرية · دون اتصال · جاهزة للطباعة", startLearning: "ابدأ التعلم", browseLibrary: "تصفح المكتبة", downloadPrint: "تحميل / طباعة", statsArticles: "مقالات معرفية", statsStages: "مراحل التعافي", statsOffline: "جاهز للعمل دون اتصال", statsDeps: "صفر تبعيات خارجية", level: "المستوى", coreKnowledge: "المعرفة الأساسية", deepDives: "تعمق — المسار الحرج", interactiveTree: "شجرة تقنية تفاعلية →", designPrinciples: "مبادئ التصميم", builtForPermanence: "مصمم لل permanence", offlineFirst: "دون اتصال أولاً", offlineFirstDesc: "كل مقال هو HTML ثابت. حمّل ZIP وتعمل المكتبة بأكملها بدون كهرباء أو شبكة أو خوادم.", printIsPermanent: "الطباعة permanence", printIsPermanentDesc: "تتعطل شبكات الكهرباء. تموت الشاشات. الورق ي survive两者." },
  about: { title: "عن مشروع التعافي الحضاري", whyExists: "لماذا هذا موجود", theSources: "المصادر", howToUse: "كيف تستخدمه", thePrinciples: "المبادئ", contribute: "المساهمة" },
  downloads: { title: "التحميلات", tagline: "الرقمي مؤقت. الطباعة permanence.", recommended: "موصى به", fullArchiveTitle: "تحميل الأرشيف الكامل", fullArchiveAction: "تحميل ZIP", printableTitle: "نسخة قابلة للطباعة", printableAction: "فتح حزم الطباعة", sourceTitle: "المستودع المصدري", sourceAction: "عرض على GitHub", version: "الإصدار", lastUpdated: "آخر تحديث", articles: "مقالات", totalSize: "الحجم الإجمالي", fitsUSB: "يناسب أي USB", redundancyDoctrine: "مبدأ التكرار" },
  library: { title: "المكتبة", tagline: "الفهرس الكامل", searchPlaceholder: "بحث في المقالات…", allStages: "جميع المراحل" },
  search: { title: "بحث", tagline: "اعثر عليه بسرعة", searchPlaceholder: "بحث في المقالات والكلمات والفئات…" },
  techTree: { title: "الشجرة التقنية", tagline: "رسم بياني تفاعلي للتبعيات", graphView: "عرض الرسم", listView: "عرض القائمة", rules: "قواعد الشجرة", resetProgress: "إعادة تعيين التقدم", resetConfirm: "إعادة تعيين كل تقدم الإتقان على هذا الجهاز؟" },
  techArticle: { home: "الرئيسية", library: "المكتبة", level: "المستوى", risk: "المخاطر", coreTechnology: "التقنية الأساسية", difficulty: "الصعوبة", levelRequired: "المستوى المطلوب", studyTime: "وقت الدراسة", stage: "المرحلة", requiredKnowledge: "المعرفة المطلوبة", noPrerequisites: "بدون شروط مسبقة — هذه تقنية أساسية.", knowledgeValidation: "التحقق من المعرفة", allChecksPass: "جميع الفحوصات ناجحة.", specifications: "المواصفات", materials: "المواد", energy: "الطاقة", people: "الأفراد", reference: "المرجع", scavengeBeforeBuilding: "اجمع قبل البناء", unlocksNext: "يفتح التالية", dependencies: "التبعيات", noDependencies: "بدون تبعيات.", markAsMastered: "تحديد كمتقن", masteredUndo: "متقن — انقر للتراجع", printThisGuide: "طباعة هذا الدليل", exportOptions: "خيارات التصدير", relatedArticles: "مقالات ذات صلة" },
  ladder: { title: "سلالم إعادة البناء", framework: "الإطار", drStoneParallel: "对应的石纪元", backToLadder: "← السلالم" },
  print: { title: "حزم الطباعة", tagline: "الورق survives", subtitle: "تتعطل شبكات الكهرباء. تموت الشاشات. الورق permanence.", starterKit: "طقم البداية", starterKitAction: "فتح جميع أدلة A0", communityManual: "الدليل المجتمعي", communityManualAction: "فتح جميع أدلة A1", bootstrappersPack: "حزمة المبتكرين", bootstrappersPackAction: "فتح جميع أدلة A2", printingTips: "نصائح الطباعة" },
  levels: {
    A0: { name: "خط الأساس للبقاء", timeframe: "أيام – أسابيع", question: "هل يمكن للبشر البقاء على قيد الحياة؟", description: "الماء والنار والمأوى والإسعافات الأولية وأول الأدوات اليدوية.", drStone: "ثلاثة أشهر الأولى لـ Senku: أدوات حجرية، حبل، مثقاب قوس، نار." },
    A1: { name: "مجتمع مستقر", timeframe: "أشهر – سنوات", question: "هل يمكن للناس العيش هنا بشكل مستدام؟", description: "الزراعة وحفظ الطعام والمأوى الدائم والصرف الصحي والصابون.", drStone: "قرية إيشيغامي: الزراعة والخزف والنسيج وطريقة حياة مستقرة." },
    A2: { name: "البذرة الصناعية", timeframe: "سنوات – عقود", question: "هل يمكننا بدء الصناعة؟", description: "نقطة التسارع غير الخطية. الفحم والحديد والكيمياء والمخرطة والبخار والكهرباء.", drStone: "مملكة العلوم: الفرن العالي وحمض الكبريتيك والمولدات والراديو." },
    A3: { name: "استعادة البنية التحتية", timeframe: "عقود", question: "هل يمكن للأنظمة التوسع ما وراء بلدة واحدة؟", description: "شبكات المياه الإقليمية والشبكات الكهربائية وسكك الحديد.", drStone: "البرسيس، GPS، السدود الكهرومائية." },
    A4: { name: "الصناعة والعلوم المتقدمة", timeframe: "أجيال", question: "الدقة والتحسين والبحث", description: "إلكترونيات الترانزستور والمتكاملات والكيمياء الحديثة.", drStone: "طريق السيليكون والأنابيب المفرغة." },
    A5: { name: "الحدود والقفزات", timeframe: "آفاق بعيدة", question: "أنظمة عالية التبعية للمستقبل", description: "الطيران الفضائي والأقمار الصناعية والتكنولوجيا الحيوية المتقدمة.", drStone: "المهمة القمرية، التواصل مع Why-Man." }
  },
  stages: {
    survival: { name: "البقاء", question: "هل يمكننا البقاء على قيد الحياة؟", description: "الماء والنار والمأوى وأول الأدوات اليدوية." },
    settlement: { name: "الاستيطان", question: "هل يمكننا العيش هنا إلى الأبد؟", description: "مأوى دائم وصرف صحي ونظافة ومجتمع." },
    agriculture: { name: "الزراعة", question: "هل يمكننا إطعام أنفسنا بشكل موثوق؟", description: "الزراعة وحفظ البذور والحفظ وتربية الحيوانات." },
    craftsmanship: { name: "الحِرَف", question: "هل يمكننا صنع الأشياء بشكل جيد؟", description: "الفخار والمنسوجات والزجاج والورق." },
    metallurgy: { name: "علم المعادن", question: "هل يمكننا استخراج وتشكيل المعادن؟", description: "الفحم والحديد والفولاذ والنحاس." },
    engineering: { name: "الهندسة", question: "هل يمكننا بناء الآلات؟", description: "القياس والمخرطة وطاقة الماء والمحرك البخاري." },
    electricity: { name: "الكهرباء", question: "هل يمكننا ترويض الإلكترون؟", description: "المولدات والبطاريات وشجرة الاتصالات." },
    industry: { name: "الصناعة", question: "هل يمكن للأنظمة التوسع ما وراء بلدة؟", description: "الكيمياء على نطاق واسع والنقل والبنية التحتية الإقليمية." },
    digital: { name: "التكنولوجيا الرقمية", question: "هل يمكننا الحساب مرة أخرى؟", description: "الإلكترونيات والحوسبة وعودة البحث." },
    space: { name: "عصر الفضاء", question: "هل يمكننا مغادرة المهد؟", description: "الطيران الفضائي والصواريخ والأنظمة عالية التبعية." }
  },
  sections: {
    survival: { title: "البقاء", subtitle: "الأولوية 1 — إبقاء الناس أحياء", description: "الماء والنار والمأوى والطعام والنظافة والإسعافات الأولية." },
    settlement: { title: "الاستيطان", subtitle: "الأولوية 2 — العيش هنا إلى الأبد", description: "مأوى دائم وصرف صحي وهيكل اجتماعي." },
    agriculture: { title: "الزراعة", subtitle: "الأولوية 2 — إطعام الناس بشكل موثوق", description: "الزراعة وحفظ البذور والحفاظ على الطعام وتربية الحيوانات." },
    medicine: { title: "الطب", subtitle: "الأولوية 1 — العدوى تقتل أكثر من الإصابة", description: "علاج الجروح والنظافة والمعرفة بالأعشاب." },
    science: { title: "العلوم", subtitle: "الأولوية 4 — الطريقة وراء إعادة البناء", description: "المنهج العلمي المادي: القياس والكيمياء والتجارب القابلة للتكرار." },
    engineering: { title: "الهندسة", subtitle: "الأولوية 3 — الآلات والطاقة", description: "الميكانيكا والمواد وعلم المعادن والآلات." },
    industry: { title: "الصناعة", subtitle: "الأولوية 5 — التوسع ما وراء بلدة", description: "التصنيع والكيمياء والنقل والاتصالات على نطاق إقليمي." }
  },
  sidebar: { knowledgeTree: "شجرة المعرفة", groups: { survival: { label: "البقاء", subsections: { "s-water": "الماء", "s-shelter": "المأوى", "s-fire": "النار", "s-food": "الطعام", "s-med": "الطب", "s-tools": "الأدوات والمواد" } }, science: { label: "العلوم", subsections: { "c-chem": "الكيمياء", "c-measure": "القياس" } }, engineering: { label: "الهندسة", subsections: { "e-met": "علم المعادن", "e-mach": "الآلات", "e-power": "الطاقة", "e-comms": "الاتصالات" } }, community: { label: "المجتمع", subsections: { "g-gov": "الحوكمة" } } } },
  categories: { Survival: "البقاء", Shelter: "المأوى", "Food & Water": "الطعام والماء", Community: "المجتمع", Power: "الطاقة", Metallurgy: "علم المعادن", Chemistry: "الكيمياء", "Machine Tools:": "آلات", Communications: "الاتصالات", Transport: "النقل", Metrology: "علم القياس", Infrastructure: "البنية التحتية", Electronics: "الإلكترونيات", Computing: "الحوسبة", Frontier: "الحدود" },
  safety: { LOW: "مخاطر منخفضة", MODERATE: "مخاطر متوسطة", HIGH: "مخاطر عالية", EXTREME: "مخاطر شديدة" },
  common: { home: "الرئيسية", articles: "مقالات", level: "المستوى", core: "أساسي", mastered: "متقن", available: "متاح", locked: "مقفل", criticalPath: "المسار الحرج", missingPrerequisite: "شرط مسبق مفقود" }
};
const ar = skeleton(en, arOverrides);
write('ar', ar);

/* ======================== PORTUGUESE (skeleton) ======================== */
const ptOverrides = {
  site: { title: "Projeto de Recuperação Civilizacional", shortTitle: "PRC", description: "O conhecimento completo necessário para reconstruir a civilização do zero." },
  nav: { home: "Início", survival: "Sobrevivência", science: "Ciência", engineering: "Engenharia", medicine: "Medicina", agriculture: "Agricultura", industry: "Indústria", library: "Biblioteca", downloads: "Downloads" },
  aria: { toggleSidebar: "Alternar barra lateral", searchLibrary: "Pesquisar na biblioteca", toggleDarkMode: "Alternar modo escuro" },
  footer: { mission: "Missão", knowledgeSections: "Seções de conhecimento", downloads: "Downloads", offlineLibrary: "Biblioteca offline", printableEdition: "Edição imprimível", fullLibraryIndex: "Índice completo", sourceZIP: "Código-fonte ZIP", openSource: "Código aberto · Livre para copiar, imprimir e redistribuir" },
  home: { heroTagline: "Backup operacional da humanidade · Offline · Pronto para imprimir", startLearning: "Começar a Aprender", browseLibrary: "Explorar Biblioteca", downloadPrint: "Baixar / Imprimir", statsArticles: "Artigos de conhecimento", statsStages: "Etapas de recuperação", statsOffline: "Pronto offline", statsDeps: "Zero dependências externas", level: "Nível", coreKnowledge: "Conhecimento básico", deepDives: "Aprofundamentos — caminho crítico", interactiveTree: "Árvore tecnológica interativa →", designPrinciples: "Princípios de design", builtForPermanence: "Construído para permanência", offlineFirst: "Offline primeiro", offlineFirstDesc: "Cada artigo é HTML estático. Baixe o ZIP e toda a biblioteca funciona sem eletricidade, rede ou servidores.", printIsPermanent: "Impressão é permanente", printIsPermanentDesc: "Redes elétricas falham. Telas morrem. Papel sobrevive a ambos.", validatedReproducible: "Validado e reproduzível", validatedReproducibleDesc: "Cada procedimento lista materiais, ferramentas, passos e a ciência por trás." },
  about: { title: "Sobre o Projeto de Recuperação Civilizacional", whyExists: "Por que isso existe", theSources: "As fontes", howToUse: "Como usar", thePrinciples: "Os princípios", contribute: "Contribuir" },
  downloads: { title: "Downloads", tagline: "Digital é temporário. Impressão é permanente.", recommended: "Recomendado", fullArchiveTitle: "Baixar Arquivo Completo", fullArchiveAction: "Baixar ZIP", printableTitle: "Edição Imprimível", printableAction: "Abrir pacotes de impressão", sourceTitle: "Repositório Fonte", sourceAction: "Ver no GitHub", version: "Versão", lastUpdated: "Última atualização", articles: "Artigos", totalSize: "Tamanho total", fitsUSB: "Cabe em qualquer USB", redundancyDoctrine: "Doutrina de redundância" },
  library: { title: "Biblioteca", tagline: "Índice completo", searchPlaceholder: "Pesquisar artigos…", allStages: "Todas as etapas" },
  search: { title: "Pesquisa", tagline: "Encontre rápido", searchPlaceholder: "Pesquisar artigos, palavras-chave, categorias…" },
  techTree: { title: "Árvore Tecnológica", tagline: "Grafo interativo de dependências", graphView: "Vista em grafo", listView: "Vista em lista", rules: "Regras da árvore", resetProgress: "Redefinir progresso", resetConfirm: "Redefinir todo o progresso de domínio neste dispositivo?" },
  techArticle: { home: "Início", library: "Biblioteca", level: "Nível", risk: "Risco", coreTechnology: "Tecnologia básica", difficulty: "Dificuldade", levelRequired: "Nível necessário", studyTime: "Tempo de estudo", stage: "Etapa", requiredKnowledge: "Conhecimento necessário", noPrerequisites: "Sem pré-requisitos — esta é uma tecnologia fundamental.", knowledgeValidation: "Validação de conhecimento", allChecksPass: "Todas as verificações passam.", specifications: "Especificações", materials: "Materiais", energy: "Energia", people: "Pessoas", reference: "Referência", scavengeBeforeBuilding: "Recuperar antes de construir", unlocksNext: "Desbloqueia próximo", dependencies: "Dependências", noDependencies: "Sem dependências.", markAsMastered: "Marcar como dominado", masteredUndo: "Dominado — clique para desfazer", printThisGuide: "Imprimir este guia", exportOptions: "Opções de exportação", relatedArticles: "Artigos relacionados" },
  ladder: { title: "A Escada de Reconstrução", framework: "O quadro", drStoneParallel: "Paralelo Dr. Stone", backToLadder: "← A Escada" },
  print: { title: "Pacotes de Impressão", tagline: "Papel sobrevive", subtitle: "Redes elétricas falham. Telas morrem. Papel é permanente.", starterKit: "Kit Inicial", starterKitDesc: "Tudo em A0 — água, fogo, abrigo, primeiros socorros.", starterKitAction: "Abrir todos os guias A0", communityManual: "Manual Comunitário", communityManualDesc: "A1 — agricultura, conservação, sabão, saneamento.", communityManualAction: "Abrir todos os guias A1", bootstrappersPack: "Pacote do Pioneiro", bootstrappersPackDesc: "A2 — carvão, ferro, ácido sulfúrico, vapor, eletricidade.", bootstrappersPackAction: "Abrir todos os guias A2", printingTips: "Dicas de impressão" },
  levels: {
    A0: { name: "Base de Sobrevivência", timeframe: "Dias – Semanas", question: "Os humanos podem sobreviver?", description: "Água, fogo, abrigo, primeiros socorros e as primeiras ferramentas feitas à mão.", drStone: "Os primeiros três meses de Senku: ferramentas de pedra, corda, broca de arco, fogo." },
    A1: { name: "Comunidade Estabilizada", timeframe: "Meses – Anos", question: "As pessoas podem viver aqui sustentavelmente?", description: "Agricultura, conservação de alimentos, abrigo permanente, saneamento, sabão.", drStone: "Vila Ishigami: agricultura, cerâmica, tecelagem, vida sedentária." },
    A2: { name: "Semente Industrial", timeframe: "Anos – Décadas", question: "Podemos iniciar a indústria?", description: "O ponto de aceleração não linear. Carvão, ferro, química, torno, vapor e eletricidade.", drStone: "O Reino da Ciência: alto-forno, ácido sulfúrico, geradores, rádio." },
    A3: { name: "Recuperação de Infraestrutura", timeframe: "Décadas", question: "Os sistemas podem escalar além de uma cidade?", description: "Redes hidráulicas regionais, redes elétricas, ferrovias.", drStone: "O Perseus, GPS, barragens hidrelétricas." },
    A4: { name: "Indústria e Ciência Avançada", timeframe: "Gerações", question: "Precisão, otimização, pesquisa", description: "Eletrônica de transistores, circuitos integrados, química moderna.", drStone: "A rota do silício, tubos de vácuo, computador parametron." },
    A5: { name: "Fronteira e Saltos", timeframe: "Horizonte distante", question: "Sistemas de alta dependência para sociedades futuras", description: "Aeroespacial, satélites e biotecnologia avançada.", drStone: "A missão lunar, contato com Why-Man." }
  },
  stages: {
    survival: { name: "Sobrevivência", question: "Podemos sobreviver?", description: "Água, fogo, abrigo e as primeiras ferramentas feitas à mão." },
    settlement: { name: "Assentamento", question: "Podemos viver aqui permanentemente?", description: "Abrigo permanente, saneamento, higiene e comunidade." },
    agriculture: { name: "Agricultura", question: "Podemos nos alimentar de forma confiável?", description: "Agricultura, preservação de sementes, conservação e pecuária." },
    craftsmanship: { name: "Artesanato", question: "Podemos fazer coisas bem?", description: "Cerâmica, têxteis, vidro, papel e a mentalidade de precisão." },
    metallurgy: { name: "Metalurgia", question: "Podemos extrair e moldar metal?", description: "Carvão, ferro, aço, cobre — os materiais de tudo mais." },
    engineering: { name: "Engenharia", question: "Podemos construir máquinas?", description: "Medição, torno, energia hidráulica e a máquina a vapor." },
    electricity: { name: "Eletricidade", question: "Podemos aproveitar o elétron?", description: "Geradores, baterias e a árvore de comunicações." },
    industry: { name: "Indústria", question: "Os sistemas podem escalar além de uma cidade?", description: "Química em escala, transporte e infraestrutura regional." },
    digital: { name: "Tecnologia Digital", question: "Podemos computar novamente?", description: "Eletrônica, computação e o retorno da pesquisa." },
    space: { name: "Era Espacial", question: "Podemos deixar o berço?", description: "Aeroespacial, foguetes e sistemas de alta dependência." }
  },
  sections: {
    survival: { title: "Sobrevivência", subtitle: "Prioridade 1 — manter as pessoas vivas", description: "Água, fogo, abrigo, comida, higiene e primeiros socorros." },
    settlement: { title: "Assentamento", subtitle: "Prioridade 2 — viver aqui permanentemente", description: "Abrigo permanente, saneamento e estruturas sociais." },
    agriculture: { title: "Agricultura", subtitle: "Prioridade 2 — alimentar as pessoas de forma confiável", description: "Agricultura, preservação de sementes, conservação e pecuária." },
    medicine: { title: "Medicina", subtitle: "Prioridade 1 — infecção mata mais que ferimento", description: "Cuidados de feridas, higiene, conhecimento herbal." },
    science: { title: "Ciência", subtitle: "Prioridade 4 — o método por trás da reconstrução", description: "O método científico físico: medição, química e experimentos reproduzíveis." },
    engineering: { title: "Engenharia", subtitle: "Prioridade 3 — máquinas e energia", description: "Mecânica, materiais, metalurgia e máquinas." },
    industry: { title: "Indústria", subtitle: "Prioridade 5 — escalar além de uma cidade", description: "Fabricação, química, transporte e comunicação em escala regional." }
  },
  sidebar: { knowledgeTree: "Árvore de conhecimento", groups: { survival: { label: "Sobrevivência", subsections: { "s-water": "Água", "s-shelter": "Abrigo", "s-fire": "Fogo", "s-food": "Comida", "s-med": "Medicina", "s-tools": "Ferramentas e Materiais" } }, science: { label: "Ciência", subsections: { "c-chem": "Química", "c-measure": "Medição" } }, engineering: { label: "Engenharia", subsections: { "e-met": "Metalurgia", "e-mach": "Máquinas", "e-power": "Energia", "e-comms": "Comunicação" } }, community: { label: "Comunidade", subsections: { "g-gov": "Governança" } } } },
  categories: { Survival: "Sobrevivência", Shelter: "Abrigo", "Food & Water": "Comida e Água", Community: "Comunidade", Power: "Energia", Metallurgy: "Metalurgia", Chemistry: "Química", "Machine Tools": "Ferramentas", Communications: "Comunicações", Transport: "Transporte", Metrology: "Metrologia", Infrastructure: "Infraestrutura", Electronics: "Eletrônica", Computing: "Computação", Frontier: "Fronteira" },
  safety: { LOW: "Baixo risco", MODERATE: "Risco moderado", HIGH: "Alto risco", EXTREME: "Risco extremo" },
  common: { home: "Início", articles: "artigos", level: "Nível", core: "Básico", mastered: "Dominado", available: "Disponível", locked: "Bloqueado", criticalPath: "Caminho crítico", missingPrerequisite: "Pré-requisito faltando" }
};
const pt = skeleton(en, ptOverrides);
write('pt', pt);

console.log('All dictionaries generated.');
